version: '3.3'

services:

  web_app:
    container_name: lucia_copilot_app
    build:
        context: ..
        dockerfile: .Dockerfile

    image: lucia_copilot_app:latest

    volumes:
      # Added for tracing npm actions
      - /home/docker-apps/lucia_copilot_app/environs:/home/environs
      - /home/docker-apps/lucia_copilot_app/.npm:/root/.npm

    ports:
      - "${LAUNCH_HTTP_PORT}:80"
